### ISSUE TITLE
exception thrown while adding new annotations

### ISSUE THREAD

**Issue by pnrobinson** [pnrobinson/hphenote#18]
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at org.monarchinitiative.phenotefx.gui.editrow.EditRowFactory.showPublicationEditDialog(EditRowFactory.java:45)
	at org.monarchinitiative.phenotefx.gui.main.PhenotePresenter.lambda$null$40(PhenotePresenter.java:1016)

**Comment by pnrobinson** [comment]
addressed this.
