### ISSUE TITLE
java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding

### ISSUE THREAD

**Issue by pnrobinson** [pnrobinson/hphenote#99]
This throws an error on M1 mac but works fine with linux. It is preventing the tree browser from initializing.

Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in unnamed module @0x6e9498ce) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to unnamed module @0x6e9498ce
	at org.controlsfx.control.textfield.AutoCompletionBinding.<init>(AutoCompletionBinding.java:538)
	at impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:107)
	at impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:92)
	at org.monarchinitiative.phenotefx.gui.widget.WidthAwareTextFields.bindWidthAwareAutoCompletion(WidthAwareTextFields.java:47)
	at org.monarchinitiative.phenotefx.gui.PhenoteController.setupAutocomplete(PhenoteController.java:526)
	at org.monarchinitiative.phenotefx.gui.PhenoteController.lambda$initialize$1(PhenoteController.java:291)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.graphics/javafx.concurrent.Task.fireEvent(Task.java:1359)
	at javafx.graphics/javafx.concurrent.Task.setState(Task.java:725)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.lambda$call$1(Task.java:1437)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by pnrobinson** [comment]
Try this: https://github.com/controlsfx/controlsfx/wiki/Using-ControlsFX-with-JDK-9-and-above

**Comment by pnrobinson** [comment]
seems to be fixed now
